# Generated by Django 4.2.16 on 2024-10-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storapp', '0002_imagememory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagememory',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
