# Generated by Django 4.2.16 on 2024-10-29 04:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storapp', '0003_alter_imagememory_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='codememory',
            name='unlock_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7),
        ),
        migrations.AddField(
            model_name='imagememory',
            name='unlock_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=7),
        ),
    ]
